// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_server_by_id.sql

package db

import (
	"context"
)

const delete_server_by_id = `-- name: delete_server_by_id :exec
DELETE FROM servers WHERE id = $1
`

// Rust: src/tugbot/servers.rs stale-row cleanup in get_servers —
// `diesel::delete(servers.filter(id.eq(server_id)))`
func (q *Queries) delete_server_by_id(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, delete_server_by_id, id)
	return err
}
