// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_gulag_user_by_id.sql

package db

import (
	"context"
)

const delete_gulag_user_by_id = `-- name: delete_gulag_user_by_id :exec
DELETE FROM gulag_users WHERE id = $1
`

// Rust: src/handlers/gulag/mod.rs run_gulag_check (release + 404-cleanup) and
// gulag_remove_handler.rs — `diesel::delete(gulag_users.filter(id.eq(...)))`
func (q *Queries) delete_gulag_user_by_id(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, delete_gulag_user_by_id, id)
	return err
}
