// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_gulag_user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insert_gulag_user = `-- name: insert_gulag_user :one
INSERT INTO gulag_users (user_id, guild_id, gulag_role_id, channel_id, in_gulag, gulag_length, created_at, release_at, message_id)
VALUES ($1, $2, $3, $4, true, $5, $6, $7, $8)
RETURNING id
`

type insert_gulag_userParams struct {
	UserID      int64
	GuildID     int64
	GulagRoleID int64
	ChannelID   int64
	GulagLength int32
	CreatedAt   pgtype.Timestamp
	ReleaseAt   pgtype.Timestamp
	MessageID   int64
}

// Rust: src/db/mod.rs send_to_gulag — `diesel::insert_into(gulag_users::table).values(&new_user).get_result`
// (release_at = created_at + gulag_length * 1s, computed in Go before the call)
// NOTE: the `remod` column exists in Rust's hand-maintained schema.rs but is
// never created by any migration (schema drift). Rust writes remod=false; the
// column default is false, so this INSERT omits the column and works against
// both the production shape and a fresh baseline shape.
func (q *Queries) insert_gulag_user(ctx context.Context, arg insert_gulag_userParams) (int32, error) {
	row := q.db.QueryRow(ctx, insert_gulag_user,
		arg.UserID,
		arg.GuildID,
		arg.GulagRoleID,
		arg.ChannelID,
		arg.GulagLength,
		arg.CreatedAt,
		arg.ReleaseAt,
		arg.MessageID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
