// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_gulag_vote.sql

package db

import (
	"context"
)

const insert_gulag_vote = `-- name: insert_gulag_vote :one
INSERT INTO gulag_votes (requester_id, sender_id, guild_id, channel_id, gulag_role_id, processed, message_id, created_at)
VALUES ($1, $2, $3, $4, $5, false, $6, now())
RETURNING id
`

type insert_gulag_voteParams struct {
	RequesterID int64
	SenderID    int64
	GuildID     int64
	ChannelID   int64
	GulagRoleID int64
	MessageID   int64
}

// Rust: src/db/mod.rs new_gulag_vote — `diesel::insert_into(gulag_votes::table).values(&new_gulag_vote).get_result`
func (q *Queries) insert_gulag_vote(ctx context.Context, arg insert_gulag_voteParams) (int32, error) {
	row := q.db.QueryRow(ctx, insert_gulag_vote,
		arg.RequesterID,
		arg.SenderID,
		arg.GuildID,
		arg.ChannelID,
		arg.GulagRoleID,
		arg.MessageID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
