// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_server.sql

package db

import (
	"context"
)

const insert_server = `-- name: insert_server :one
INSERT INTO servers (guild_id, gulag_id) VALUES ($1, $2)
RETURNING id
`

type insert_serverParams struct {
	GuildID int64
	GulagID int64
}

// Rust: src/db/mod.rs create_server — `diesel::insert_into(servers::table).values(&new_server).get_result`
func (q *Queries) insert_server(ctx context.Context, arg insert_serverParams) (int32, error) {
	row := q.db.QueryRow(ctx, insert_server, arg.GuildID, arg.GulagID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
