// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_ai_slop_usage.sql

package db

import (
	"context"
)

const insert_ai_slop_usage = `-- name: insert_ai_slop_usage :one
INSERT INTO ai_slop_usage (user_id, guild_id, usage_count, last_slop_at, created_at)
VALUES ($1, $2, 0, now(), now())
RETURNING id
`

type insert_ai_slop_usageParams struct {
	UserID  int64
	GuildID int64
}

// Rust: src/db/mod.rs get_or_create_ai_slop_usage (the insert half, on NotFound)
func (q *Queries) insert_ai_slop_usage(ctx context.Context, arg insert_ai_slop_usageParams) (int32, error) {
	row := q.db.QueryRow(ctx, insert_ai_slop_usage, arg.UserID, arg.GuildID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
