// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_is_this_real_usage.sql

package db

import (
	"context"
)

const insert_is_this_real_usage = `-- name: insert_is_this_real_usage :one
INSERT INTO is_this_real_usage (user_id, guild_id, last_used_at, created_at)
VALUES ($1, $2, now(), now())
RETURNING id
`

type insert_is_this_real_usageParams struct {
	UserID  int64
	GuildID int64
}

// Rust: src/db/mod.rs get_or_create_is_this_real_usage (the insert half, on NotFound)
func (q *Queries) insert_is_this_real_usage(ctx context.Context, arg insert_is_this_real_usageParams) (int32, error) {
	row := q.db.QueryRow(ctx, insert_is_this_real_usage, arg.UserID, arg.GuildID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
