// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_goku_poll_usage.sql

package db

import (
	"context"
)

const insert_goku_poll_usage = `-- name: insert_goku_poll_usage :one
INSERT INTO goku_poll_usage (user_id, guild_id, usage_count, last_goku_at, created_at)
VALUES ($1, $2, 0, now(), now())
RETURNING id
`

type insert_goku_poll_usageParams struct {
	UserID  int64
	GuildID int64
}

// Rust: src/db/mod.rs get_or_create_goku_poll_usage (the insert half, on NotFound)
func (q *Queries) insert_goku_poll_usage(ctx context.Context, arg insert_goku_poll_usageParams) (int32, error) {
	row := q.db.QueryRow(ctx, insert_goku_poll_usage, arg.UserID, arg.GuildID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
