// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_message_vote.sql

package db

import (
	"context"
)

const insert_message_vote = `-- name: insert_message_vote :one
INSERT INTO message_votes (message_id, channel_id, guild_id, user_id,
                          current_vote_tally, total_vote_tally, voters, job_status)
VALUES ($1, $2, $3, $4,
        $5, 0, $6::bigint[], 'created')
RETURNING message_id, channel_id, guild_id, user_id, total_vote_tally,
          voters, job_status, current_vote_tally
`

type insert_message_voteParams struct {
	MessageID        int64
	ChannelID        int64
	GuildID          int64
	UserID           int64
	CurrentVoteTally int32
	Voters           []int64
}

// Rust: src/db/message_vote.rs (the None branches of sync_from_discord /
// message_vote_create_or_update) — `diesel::insert_into(message_votes::table)...returning(...)`
func (q *Queries) insert_message_vote(ctx context.Context, arg insert_message_voteParams) (MessageVote, error) {
	row := q.db.QueryRow(ctx, insert_message_vote,
		arg.MessageID,
		arg.ChannelID,
		arg.GuildID,
		arg.UserID,
		arg.CurrentVoteTally,
		arg.Voters,
	)
	var i MessageVote
	err := row.Scan(
		&i.MessageID,
		&i.ChannelID,
		&i.GuildID,
		&i.UserID,
		&i.TotalVoteTally,
		&i.Voters,
		&i.JobStatus,
		&i.CurrentVoteTally,
	)
	return i, err
}
