// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type JobStatus string

const (
	JobStatusCreated JobStatus = "created"
	JobStatusRunning JobStatus = "running"
	JobStatusDone    JobStatus = "done"
	JobStatusFailure JobStatus = "failure"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus
	Valid     bool // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type AiSlopUsage struct {
	ID         int32
	UserID     int64
	GuildID    int64
	UsageCount int32
	LastSlopAt pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
}

type DieselSchemaMigration struct {
	Version string
	RunOn   pgtype.Timestamp
}

type Feature struct {
	ID      int32
	Name    string
	Enabled bool
}

type GokuPollUsage struct {
	ID         int32
	UserID     int64
	GuildID    int64
	UsageCount int32
	LastGokuAt pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
}

type GulagUser struct {
	ID          int32
	UserID      int64
	GuildID     int64
	GulagRoleID int64
	ChannelID   int64
	InGulag     bool
	GulagLength int32
	CreatedAt   pgtype.Timestamp
	ReleaseAt   pgtype.Timestamp
	MessageID   int64
}

type GulagVote struct {
	ID          int32
	RequesterID int64
	SenderID    int64
	GuildID     int64
	ChannelID   int64
	GulagRoleID int64
	Processed   bool
	MessageID   int64
	CreatedAt   pgtype.Timestamp
}

type IsThisRealUsage struct {
	ID         int32
	UserID     int64
	GuildID    int64
	LastUsedAt pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
}

type MessageVote struct {
	MessageID        int64
	ChannelID        int64
	GuildID          int64
	UserID           int64
	TotalVoteTally   int32
	Voters           []int64
	JobStatus        JobStatus
	CurrentVoteTally int32
}

type ReversalOfFortune struct {
	UserID            int64
	CurrentPercentage int64
}

type Server struct {
	ID      int32
	GuildID int64
	GulagID int64
}

type UserActivity struct {
	UserID        int64
	GuildID       int64
	LastMessageAt pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
}
