// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_gulag_users_in_gulag_for_guild.sql

package db

import (
	"context"
)

const select_gulag_users_in_gulag_for_guild = `-- name: select_gulag_users_in_gulag_for_guild :many
SELECT id, user_id, guild_id, gulag_role_id, channel_id, in_gulag,
       gulag_length, created_at, release_at, message_id
FROM gulag_users WHERE in_gulag AND guild_id = $1
`

// Rust: src/handlers/gulag/gulag_list_handler.rs —
// `gulag_users.filter(in_gulag.eq(true)).filter(guild_id.eq(...)).load()`
// NOTE: `remod` (present in Rust schema.rs, absent from all migrations) is
// omitted from the projection so this works against both DB shapes.
func (q *Queries) select_gulag_users_in_gulag_for_guild(ctx context.Context, guildID int64) ([]GulagUser, error) {
	rows, err := q.db.Query(ctx, select_gulag_users_in_gulag_for_guild, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GulagUser
	for rows.Next() {
		var i GulagUser
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GuildID,
			&i.GulagRoleID,
			&i.ChannelID,
			&i.InGulag,
			&i.GulagLength,
			&i.CreatedAt,
			&i.ReleaseAt,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
