// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_message_vote_user_id.sql

package db

import (
	"context"
)

const select_message_vote_user_id = `-- name: select_message_vote_user_id :one
SELECT user_id FROM message_votes WHERE message_id = $1
`

// Rust: src/db/message_vote.rs get_user_id_from_message —
// `message_votes.find(message_id as i64).select(message_votes::user_id).first().optional()`
func (q *Queries) select_message_vote_user_id(ctx context.Context, messageID int64) (int64, error) {
	row := q.db.QueryRow(ctx, select_message_vote_user_id, messageID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}
