// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_user_activity_for_ids.sql

package db

import (
	"context"
)

const select_user_activity_for_ids = `-- name: select_user_activity_for_ids :many
SELECT user_id, guild_id, last_message_at, created_at
FROM user_activity
WHERE guild_id = $1 AND user_id = ANY($2::int8[])
`

type select_user_activity_for_idsParams struct {
	GuildID int64
	UserIds []int64
}

// Rust: src/db/mod.rs query_user_activity_for_ids —
// `user_activity.filter(guild_id.eq(...)).filter(user_id.eq_any(ids))`
func (q *Queries) select_user_activity_for_ids(ctx context.Context, arg select_user_activity_for_idsParams) ([]UserActivity, error) {
	rows, err := q.db.Query(ctx, select_user_activity_for_ids, arg.GuildID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserActivity
	for rows.Next() {
		var i UserActivity
		if err := rows.Scan(
			&i.UserID,
			&i.GuildID,
			&i.LastMessageAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
