// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_message_vote_by_id.sql

package db

import (
	"context"
)

const select_message_vote_by_id = `-- name: select_message_vote_by_id :one
SELECT message_id, channel_id, guild_id, user_id, total_vote_tally,
       voters, job_status, current_vote_tally
FROM message_votes WHERE message_id = $1
`

// Rust: src/db/message_vote.rs (sync_from_discord / message_vote_create_or_update /
// message_vote_remove / get_user_id_from_message) —
// `message_votes.find(message_id).select(MessageVotes::as_select()).first().optional()`
func (q *Queries) select_message_vote_by_id(ctx context.Context, messageID int64) (MessageVote, error) {
	row := q.db.QueryRow(ctx, select_message_vote_by_id, messageID)
	var i MessageVote
	err := row.Scan(
		&i.MessageID,
		&i.ChannelID,
		&i.GuildID,
		&i.UserID,
		&i.TotalVoteTally,
		&i.Voters,
		&i.JobStatus,
		&i.CurrentVoteTally,
	)
	return i, err
}
