// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_gulag_user_by_user.sql

package db

import (
	"context"
)

const select_gulag_user_by_user = `-- name: select_gulag_user_by_user :one
SELECT id, user_id, guild_id, gulag_role_id, channel_id, in_gulag,
       gulag_length, created_at, release_at, message_id
FROM gulag_users WHERE user_id = $1 AND in_gulag
`

// Rust: src/handlers/gulag/mod.rs Gulag::is_user_in_gulag —
// `gulag_users.filter(user_id.eq(...)).filter(in_gulag.eq(true)).first().optional()`
// NOTE: `remod` (present in Rust schema.rs, absent from all migrations) is
// omitted from the projection so this works against both DB shapes.
func (q *Queries) select_gulag_user_by_user(ctx context.Context, userID int64) (GulagUser, error) {
	row := q.db.QueryRow(ctx, select_gulag_user_by_user, userID)
	var i GulagUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuildID,
		&i.GulagRoleID,
		&i.ChannelID,
		&i.InGulag,
		&i.GulagLength,
		&i.CreatedAt,
		&i.ReleaseAt,
		&i.MessageID,
	)
	return i, err
}
