// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_goku_poll_usage.sql

package db

import (
	"context"
)

const select_goku_poll_usage = `-- name: select_goku_poll_usage :one
SELECT id, user_id, guild_id, usage_count, last_goku_at, created_at
FROM goku_poll_usage WHERE user_id = $1 AND guild_id = $2
`

type select_goku_poll_usageParams struct {
	UserID  int64
	GuildID int64
}

// Rust: src/db/mod.rs get_or_create_goku_poll_usage (the select half)
func (q *Queries) select_goku_poll_usage(ctx context.Context, arg select_goku_poll_usageParams) (GokuPollUsage, error) {
	row := q.db.QueryRow(ctx, select_goku_poll_usage, arg.UserID, arg.GuildID)
	var i GokuPollUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuildID,
		&i.UsageCount,
		&i.LastGokuAt,
		&i.CreatedAt,
	)
	return i, err
}
