// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_servers_all.sql

package db

import (
	"context"
)

const select_servers_all = `-- name: select_servers_all :many
SELECT id, guild_id, gulag_id FROM servers
`

// Rust: src/tugbot/servers.rs Servers::get_servers — `servers.load::<Server>`
func (q *Queries) select_servers_all(ctx context.Context) ([]Server, error) {
	rows, err := q.db.Query(ctx, select_servers_all)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Server
	for rows.Next() {
		var i Server
		if err := rows.Scan(&i.ID, &i.GuildID, &i.GulagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
