// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_pending_gulag_votes.sql

package db

import (
	"context"
)

const select_pending_gulag_votes = `-- name: select_pending_gulag_votes :many
SELECT message_id, channel_id, guild_id, user_id, total_vote_tally,
       voters, job_status, current_vote_tally
FROM message_votes
WHERE current_vote_tally >= 5
  AND job_status IN ('created', 'done')
FOR UPDATE SKIP LOCKED
`

// Rust: src/handlers/gulag/mod.rs run_gulag_vote_check —
// `message_votes.filter(current_vote_tally.ge(5)).filter(job_status_created_or_done).for_update().skip_locked().load()`
func (q *Queries) select_pending_gulag_votes(ctx context.Context) ([]MessageVote, error) {
	rows, err := q.db.Query(ctx, select_pending_gulag_votes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageVote
	for rows.Next() {
		var i MessageVote
		if err := rows.Scan(
			&i.MessageID,
			&i.ChannelID,
			&i.GuildID,
			&i.UserID,
			&i.TotalVoteTally,
			&i.Voters,
			&i.JobStatus,
			&i.CurrentVoteTally,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
