// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_is_this_real_usage.sql

package db

import (
	"context"
)

const select_is_this_real_usage = `-- name: select_is_this_real_usage :one
SELECT id, user_id, guild_id, last_used_at, created_at
FROM is_this_real_usage WHERE user_id = $1 AND guild_id = $2
`

type select_is_this_real_usageParams struct {
	UserID  int64
	GuildID int64
}

// Rust: src/db/mod.rs get_is_this_real_usage / get_or_create_is_this_real_usage (the select half)
func (q *Queries) select_is_this_real_usage(ctx context.Context, arg select_is_this_real_usageParams) (IsThisRealUsage, error) {
	row := q.db.QueryRow(ctx, select_is_this_real_usage, arg.UserID, arg.GuildID)
	var i IsThisRealUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuildID,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}
