// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_inactive_user_ids.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const select_inactive_user_ids = `-- name: select_inactive_user_ids :many
SELECT user_id FROM user_activity
WHERE guild_id = $1 AND last_message_at < $2
`

type select_inactive_user_idsParams struct {
	GuildID int64
	Cutoff  pgtype.Timestamp
}

// Rust: src/db/mod.rs query_inactive_users —
// `user_activity.filter(guild_id.eq(...)).filter(last_message_at.lt(cutoff)).select(user_id)`
func (q *Queries) select_inactive_user_ids(ctx context.Context, arg select_inactive_user_idsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, select_inactive_user_ids, arg.GuildID, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
