// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_features_all.sql

package db

import (
	"context"
)

const select_features_all = `-- name: select_features_all :many
SELECT id, name, enabled FROM features
`

// Rust: src/features/mod.rs Features::all — `features.load(&mut conn)`
func (q *Queries) select_features_all(ctx context.Context) ([]Feature, error) {
	rows, err := q.db.Query(ctx, select_features_all)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feature
	for rows.Next() {
		var i Feature
		if err := rows.Scan(&i.ID, &i.Name, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
