// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_ai_slop_usage.sql

package db

import (
	"context"
)

const select_ai_slop_usage = `-- name: select_ai_slop_usage :one
SELECT id, user_id, guild_id, usage_count, last_slop_at, created_at
FROM ai_slop_usage WHERE user_id = $1 AND guild_id = $2
`

type select_ai_slop_usageParams struct {
	UserID  int64
	GuildID int64
}

// Rust: src/db/mod.rs get_or_create_ai_slop_usage (the select half) —
// `ai_slop_usage.filter(user_id.eq(...)).filter(guild_id.eq(...)).first()`
func (q *Queries) select_ai_slop_usage(ctx context.Context, arg select_ai_slop_usageParams) (AiSlopUsage, error) {
	row := q.db.QueryRow(ctx, select_ai_slop_usage, arg.UserID, arg.GuildID)
	var i AiSlopUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuildID,
		&i.UsageCount,
		&i.LastSlopAt,
		&i.CreatedAt,
	)
	return i, err
}
