// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_server_by_guild_id.sql

package db

import (
	"context"
)

const select_server_by_guild_id = `-- name: select_server_by_guild_id :one
SELECT id, guild_id, gulag_id FROM servers WHERE guild_id = $1
`

// Rust: src/db/mod.rs get_server_by_guild_id — `servers.filter(guild_id.eq(...)).first()`
func (q *Queries) select_server_by_guild_id(ctx context.Context, guildID int64) (Server, error) {
	row := q.db.QueryRow(ctx, select_server_by_guild_id, guildID)
	var i Server
	err := row.Scan(&i.ID, &i.GuildID, &i.GulagID)
	return i, err
}
