// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_feature_enabled.sql

package db

import (
	"context"
)

const select_feature_enabled = `-- name: select_feature_enabled :one
SELECT enabled FROM features WHERE name = $1
`

// Rust: src/features/mod.rs Features::check_enabled / Features::is_enabled —
// `features.filter(name.eq(...)).select(enabled).first::<bool>(...).optional()`
func (q *Queries) select_feature_enabled(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, select_feature_enabled, name)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}
