// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select_tracked_user_ids.sql

package db

import (
	"context"
)

const select_tracked_user_ids = `-- name: select_tracked_user_ids :many
SELECT user_id FROM user_activity WHERE guild_id = $1
`

// Rust: src/db/mod.rs query_all_tracked_user_ids_for_guild —
// `user_activity.filter(guild_id.eq(...)).select(user_id)`
func (q *Queries) select_tracked_user_ids(ctx context.Context, guildID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, select_tracked_user_ids, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
