// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_message_votes_stale_reset.sql

package db

import (
	"context"
)

const update_message_votes_stale_reset = `-- name: update_message_votes_stale_reset :exec
UPDATE message_votes SET job_status = 'created' WHERE job_status = 'running'
`

// Rust: src/handlers/gulag/mod.rs run_gulag_vote_check (the 30s stale reset) —
// `diesel::update(message_votes.filter(job_status.eq(Running))).set(job_status.eq(Created))`
func (q *Queries) update_message_votes_stale_reset(ctx context.Context) error {
	_, err := q.db.Exec(ctx, update_message_votes_stale_reset)
	return err
}
