// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_gulag_user_time.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const update_gulag_user_time = `-- name: update_gulag_user_time :exec
UPDATE gulag_users SET gulag_length = $1, release_at = $2 WHERE id = $3
`

type update_gulag_user_timeParams struct {
	GulagLength int32
	ReleaseAt   pgtype.Timestamp
	ID          int32
}

// Rust: src/db/mod.rs add_time_to_gulag — `diesel::update(gulag_users.find(id)).set(gulag_length, release_at)`
func (q *Queries) update_gulag_user_time(ctx context.Context, arg update_gulag_user_timeParams) error {
	_, err := q.db.Exec(ctx, update_gulag_user_time, arg.GulagLength, arg.ReleaseAt, arg.ID)
	return err
}
