// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_message_vote_final_done.sql

package db

import (
	"context"
)

const update_message_vote_final_done = `-- name: update_message_vote_final_done :exec
UPDATE message_votes
SET job_status = 'done',
    total_vote_tally = $1,
    current_vote_tally = 0,
    voters = ARRAY[]::bigint[]
WHERE message_id = $2
`

type update_message_vote_final_doneParams struct {
	NewTotalVoteTally int32
	MessageID         int64
}

// Rust: src/handlers/gulag/mod.rs gulag_check_handler (the done branch) —
// `set(job_status=Done, total_vote_tally = current + total, current_vote_tally = 0, voters = [])`
// The sum (current + total) is computed by the caller (the loaded row carries
// both values) and passed as @new_total_vote_tally.
func (q *Queries) update_message_vote_final_done(ctx context.Context, arg update_message_vote_final_doneParams) error {
	_, err := q.db.Exec(ctx, update_message_vote_final_done, arg.NewTotalVoteTally, arg.MessageID)
	return err
}
