// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_gulag_user_release.sql

package db

import (
	"context"
)

const update_gulag_user_release = `-- name: update_gulag_user_release :exec
UPDATE gulag_users SET in_gulag = false WHERE id = $1
`

// Rust: src/handlers/gulag/mod.rs run_gulag_check release —
// `diesel::update(gulag_users.filter(id.eq(...))).set(in_gulag.eq(false))`
func (q *Queries) update_gulag_user_release(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, update_gulag_user_release, id)
	return err
}
