// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_message_vote_voters.sql

package db

import (
	"context"
)

const update_message_vote_voters = `-- name: update_message_vote_voters :exec
UPDATE message_votes
SET current_vote_tally = $1, voters = $2
WHERE message_id = $3
`

type update_message_vote_votersParams struct {
	CurrentVoteTally int32
	Voters           []int64
	MessageID        int64
}

// Rust: src/db/message_vote.rs (sync_from_discord, the ADDED branches of
// message_vote_create_or_update, and message_vote_remove) —
// `diesel::update(message_votes.find(message_id)).set(current_vote_tally, voters)`
func (q *Queries) update_message_vote_voters(ctx context.Context, arg update_message_vote_votersParams) error {
	_, err := q.db.Exec(ctx, update_message_vote_voters, arg.CurrentVoteTally, arg.Voters, arg.MessageID)
	return err
}
