// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_message_vote_status.sql

package db

import (
	"context"
)

const update_message_vote_status = `-- name: update_message_vote_status :exec
UPDATE message_votes SET job_status = $1 WHERE message_id = $2
`

type update_message_vote_statusParams struct {
	Status    JobStatus
	MessageID int64
}

// Rust: src/handlers/gulag/mod.rs (gulag_check_handler sets running; the release
// loop sets done; the vote loop sets failure on error) —
// `diesel::update(message_votes.find/....set(job_status.eq(...))`
func (q *Queries) update_message_vote_status(ctx context.Context, arg update_message_vote_statusParams) error {
	_, err := q.db.Exec(ctx, update_message_vote_status, arg.Status, arg.MessageID)
	return err
}
