// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_feature_enabled.sql

package db

import (
	"context"
)

const update_feature_enabled = `-- name: update_feature_enabled :exec
UPDATE features SET enabled = $1 WHERE name = $2
`

type update_feature_enabledParams struct {
	Enabled bool
	Name    string
}

// Rust: src/features/mod.rs Features::update — `diesel::update(...).set(enabled.eq(...))`
func (q *Queries) update_feature_enabled(ctx context.Context, arg update_feature_enabledParams) error {
	_, err := q.db.Exec(ctx, update_feature_enabled, arg.Enabled, arg.Name)
	return err
}
