// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_is_this_real_usage_last_used.sql

package db

import (
	"context"
)

const update_is_this_real_usage_last_used = `-- name: update_is_this_real_usage_last_used :exec
UPDATE is_this_real_usage SET last_used_at = now() WHERE id = $1
`

// Rust: src/db/mod.rs update_is_this_real_usage —
// `diesel::update(is_this_real_usage.find(id)).set(last_used_at)`
func (q *Queries) update_is_this_real_usage_last_used(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, update_is_this_real_usage_last_used, id)
	return err
}
