// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_ai_slop_usage.sql

package db

import (
	"context"
)

const update_ai_slop_usage = `-- name: update_ai_slop_usage :exec
UPDATE ai_slop_usage SET usage_count = $1, last_slop_at = now() WHERE id = $2
`

type update_ai_slop_usageParams struct {
	UsageCount int32
	ID         int32
}

// Rust: src/db/mod.rs increment_ai_slop_usage —
// `diesel::update(ai_slop_usage.find(id)).set(usage_count, last_slop_at)`
func (q *Queries) update_ai_slop_usage(ctx context.Context, arg update_ai_slop_usageParams) error {
	_, err := q.db.Exec(ctx, update_ai_slop_usage, arg.UsageCount, arg.ID)
	return err
}
