// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_user_activity.sql

package db

import (
	"context"
)

const upsert_user_activity = `-- name: upsert_user_activity :exec
INSERT INTO user_activity (user_id, guild_id, last_message_at, created_at)
VALUES ($1, $2, now(), now())
ON CONFLICT (user_id, guild_id) DO UPDATE
SET last_message_at = GREATEST(user_activity.last_message_at, now())
`

type upsert_user_activityParams struct {
	UserID  int64
	GuildID int64
}

// Rust: src/db/mod.rs bulk_upsert_activity —
// `insert ... on_conflict((user_id, guild_id)).do_update().set(last_message_at = GREATEST(last_message_at, excluded.last_message_at))`
// (one row per call; the Go caller loops per (user, guild) pair)
func (q *Queries) upsert_user_activity(ctx context.Context, arg upsert_user_activityParams) error {
	_, err := q.db.Exec(ctx, upsert_user_activity, arg.UserID, arg.GuildID)
	return err
}
