// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_increment_goku_poll_usage.sql

package db

import (
	"context"
)

const upsert_increment_goku_poll_usage = `-- name: upsert_increment_goku_poll_usage :one
INSERT INTO goku_poll_usage (user_id, guild_id, usage_count, last_goku_at, created_at)
VALUES ($1, $2, 1, now(), now())
ON CONFLICT (user_id, guild_id) DO UPDATE
SET usage_count = goku_poll_usage.usage_count + 1, last_goku_at = now()
RETURNING usage_count
`

type upsert_increment_goku_poll_usageParams struct {
	UserID  int64
	GuildID int64
}

// Rust: src/db/mod.rs atomic_increment_goku_poll —
// `insert ... on_conflict((user_id, guild_id)).do_update().set(usage_count = usage_count + 1, last_goku_at = now())`
func (q *Queries) upsert_increment_goku_poll_usage(ctx context.Context, arg upsert_increment_goku_poll_usageParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsert_increment_goku_poll_usage, arg.UserID, arg.GuildID)
	var usage_count int32
	err := row.Scan(&usage_count)
	return usage_count, err
}
